# Generated by Django 5.1 on 2024-09-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('tasks', '0005_alter_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='task_label', to='marks.mark'),
        ),
    ]
