# Generated by Django 5.1 on 2024-10-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('tasks', '0009_remove_task_label_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='task_label', to='marks.mark'),
        ),
    ]
